[package]
name = "evm2near"
version = "0.1.0"
edition = "2021"
rust-version = "1.63"
description = "TODO"
publish = false

[features]
default = []

[dependencies]
abi-types = { path = "../../lib/abi-types" }
relooper = { path = "../../lib/relooper" }
clap = { version = "3.2.17", features = ["color", "derive", "unicode"] }
ethnum = "1.2.2"
evm_rs = "0.3.2"
hex = "0.4.3"
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
sha3 = "0.10"
wild = "2.1.0"
wasmparser = "0.102.0"
wasm-encoder = "0.25.0"
anyhow = "1.0"
flame = "0.2.2"

[[bin]]
name = "evm2near"
path = "src/main.rs"
